export type EventStatus = "draft" | "under-review" | "rejected" | "published" | "cancelled" | "completed"

export interface TicketType {
	name: string
	price: number // 0 = free
	sold: number
	capacity: number
}

export interface MockEvent {
	id: string
	title: string
	category: string
	format: "In-Person" | "Online" | "Hybrid"
	date: string         // "YYYY-MM-DD"
	time: string         // "08:00 – 20:00"
	venue: string
	address: string
	cover: string
	status: EventStatus
	registrations: number
	capacity: number
	revenue: number
	checkedIn: number | null
	checkedInCapacity: number | null
	description: string
	visibility: string
	language: string
	age: string
	refundPolicy: string
	tags: string[]
	rejectionReason?: string
	cancellationReason?: string
	ticketTypes: TicketType[]
}

export const MOCK_EVENTS: MockEvent[] = [
	{
		id: "summer-music-festival",
		title: "Summer Music Festival",
		category: "Music",
		format: "In-Person",
		date: "2025-06-21",
		time: "12:00 – 23:00",
		venue: "Zilker Park",
		address: "2100 Barton Springs Rd, Austin, TX 78704",
		cover: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&q=80",
		status: "published",
		registrations: 1230,
		capacity: 1400,
		revenue: 210670,
		checkedIn: 3,
		checkedInCapacity: 7,
		description: "Three days of non-stop music featuring 40+ artists across 5 stages in the heart of Austin. Enjoy craft food vendors, art installations, and camping.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "Refunds up to 48 hours before",
		tags: ["music", "festival", "summer", "outdoor"],
		ticketTypes: [
			{ name: "General Admission", price: 149, sold: 843, capacity: 1000 },
			{ name: "VIP Pass", price: 349, sold: 187, capacity: 200 },
		],
	},
	{
		id: "tech-innovators-summit",
		title: "Tech Innovators Summit",
		category: "Technology",
		format: "In-Person",
		date: "2025-07-15",
		time: "09:00 – 19:00",
		venue: "Moscone Center",
		address: "747 Howard St, San Francisco, CA 94103",
		cover: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
		status: "under-review",
		registrations: 312,
		capacity: 400,
		revenue: 71688,
		checkedIn: null,
		checkedInCapacity: null,
		description: "A one-day conference bringing together 300+ tech professionals, startup founders, and investors. Keynotes, panels, workshops, and networking.",
		visibility: "Public",
		language: "English",
		age: "18+",
		refundPolicy: "Refunds up to 7 days before",
		tags: ["tech", "startup", "innovation", "networking"],
		ticketTypes: [
			{ name: "General Pass", price: 199, sold: 248, capacity: 300 },
			{ name: "Workshop Bundle", price: 349, sold: 64, capacity: 100 },
		],
	},
	{
		id: "wellness-retreat-weekend",
		title: "Wellness Retreat Weekend",
		category: "Health & Wellness",
		format: "In-Person",
		date: "2025-08-08",
		time: "08:00 – 20:00",
		venue: "Mii amo Spa & Resort",
		address: "525 Boynton Canyon Rd, Sedona, AZ 86336",
		cover: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
		status: "draft",
		registrations: 0,
		capacity: 50,
		revenue: 0,
		checkedIn: null,
		checkedInCapacity: null,
		description: "Escape the city for a transformative 3-day wellness experience. Daily yoga, meditation sessions, breathwork, mindful eating, and sound healing.",
		visibility: "Public",
		language: "English",
		age: "18+",
		refundPolicy: "No Refunds",
		tags: ["wellness", "yoga", "meditation", "retreat"],
		ticketTypes: [
			{ name: "Full Weekend Pass", price: 0, sold: 0, capacity: 50 },
		],
	},
	{
		id: "urban-photography-walk",
		title: "Urban Photography Walk",
		category: "Arts & Culture",
		format: "In-Person",
		date: "2025-06-04",
		time: "09:00 – 12:00",
		venue: "Brooklyn Bridge Park",
		address: "334 Furman St, Brooklyn, NY 11201",
		cover: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=80",
		status: "rejected",
		registrations: 0,
		capacity: 25,
		revenue: 0,
		checkedIn: null,
		checkedInCapacity: null,
		description: "A guided photography walk through NYC's most photogenic streets, led by professional photographer Marco Chen. All skill levels welcome.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "Refunds up to 24 hours before",
		tags: ["photography", "art", "NYC", "outdoors"],
		rejectionReason: "Event description needs more detail. Please clarify what equipment participants need to bring and expand your safety protocols.",
		ticketTypes: [
			{ name: "General Admission", price: 0, sold: 0, capacity: 25 },
		],
	},
	{
		id: "food-culture-fest",
		title: "Food & Culture Fest",
		category: "Food & Drink",
		format: "In-Person",
		date: "2025-09-12",
		time: "11:00 – 22:00",
		venue: "Bayfront Park",
		address: "301 N Biscayne Blvd, Miami, FL 33132",
		cover: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=1200&q=80",
		status: "cancelled",
		registrations: 0,
		capacity: 1000,
		revenue: 0,
		checkedIn: null,
		checkedInCapacity: null,
		description: "A celebration of Miami's vibrant culinary diversity with chef demos, tasting sessions, live music and cultural performances.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "Refunds up to 7 days before",
		tags: ["food", "culture", "miami", "festival"],
		cancellationReason: "Venue permit not approved by city authorities.",
		ticketTypes: [
			{ name: "Day Pass", price: 35, sold: 0, capacity: 1000 },
		],
	},
	{
		id: "night-market-experience",
		title: "Night Market Experience",
		category: "Food & Drink",
		format: "In-Person",
		date: "2025-05-30",
		time: "17:00 – 23:00",
		venue: "Tom McCall Waterfront Park",
		address: "98 SW Naito Pkwy, Portland, OR 97204",
		cover: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
		status: "completed",
		registrations: 2534,
		capacity: 2700,
		revenue: 47460,
		checkedIn: 4,
		checkedInCapacity: 5,
		description: "Portland's largest night market featuring 80+ vendors, live music, street food from 20 countries, craft beer garden, and artisan goods.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "No Refunds",
		tags: ["market", "food", "nightlife", "arts"],
		ticketTypes: [
			{ name: "General Entry", price: 15, sold: 2345, capacity: 2500 },
			{ name: "VIP Tasting Bundle", price: 65, sold: 189, capacity: 200 },
		],
	},
	{
		id: "jazz-under-stars",
		title: "Jazz Under the Stars",
		category: "Music",
		format: "In-Person",
		date: "2025-07-20",
		time: "19:00 – 23:00",
		venue: "Millennium Park",
		address: "201 E Randolph St, Chicago, IL 60601",
		cover: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
		status: "published",
		registrations: 450,
		capacity: 600,
		revenue: 22500,
		checkedIn: null,
		checkedInCapacity: null,
		description: "An enchanting evening of jazz music under the open sky at Chicago's iconic Millennium Park. Featuring world-class musicians and a beautiful outdoor setting.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "Refunds up to 48 hours before",
		tags: ["jazz", "music", "outdoor", "chicago"],
		ticketTypes: [
			{ name: "General Seating", price: 45, sold: 380, capacity: 500 },
			{ name: "Premium Seating", price: 85, sold: 70, capacity: 100 },
		],
	},
	{
		id: "startup-pitch-competition",
		title: "Startup Pitch Competition",
		category: "Business",
		format: "In-Person",
		date: "2025-08-22",
		time: "10:00 – 18:00",
		venue: "WeWork Downtown",
		address: "115 W 18th St, New York, NY 10011",
		cover: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80",
		status: "draft",
		registrations: 0,
		capacity: 150,
		revenue: 0,
		checkedIn: null,
		checkedInCapacity: null,
		description: "Watch 20 early-stage startups pitch to a panel of top VCs. Networking, mentorship, and prize money for the winners.",
		visibility: "Public",
		language: "English",
		age: "18+",
		refundPolicy: "No Refunds",
		tags: ["startup", "pitch", "VC", "entrepreneurship"],
		ticketTypes: [
			{ name: "Audience Pass", price: 0, sold: 0, capacity: 150 },
		],
	},
	{
		id: "rooftop-yoga-sunrise",
		title: "Rooftop Yoga at Sunrise",
		category: "Health & Wellness",
		format: "In-Person",
		date: "2025-06-15",
		time: "06:00 – 08:00",
		venue: "The Standard Hotel",
		address: "848 Washington St, New York, NY 10014",
		cover: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80",
		status: "completed",
		registrations: 48,
		capacity: 50,
		revenue: 1440,
		checkedIn: 48,
		checkedInCapacity: 48,
		description: "Start your morning with a rejuvenating yoga session on a Manhattan rooftop as the sun rises over the city skyline.",
		visibility: "Public",
		language: "English",
		age: "All Ages",
		refundPolicy: "Refunds up to 24 hours before",
		tags: ["yoga", "wellness", "rooftop", "sunrise"],
		ticketTypes: [
			{ name: "Session Pass", price: 30, sold: 48, capacity: 50 },
		],
	},
	{
		id: "indie-film-screening",
		title: "Indie Film Screening Night",
		category: "Arts & Culture",
		format: "In-Person",
		date: "2025-07-04",
		time: "20:00 – 23:00",
		venue: "Alamo Drafthouse",
		address: "1120 S Lamar Blvd, Austin, TX 78704",
		cover: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
		status: "under-review",
		registrations: 89,
		capacity: 120,
		revenue: 1335,
		checkedIn: null,
		checkedInCapacity: null,
		description: "A curated evening of award-winning short films from independent filmmakers around the world, followed by a Q&A with directors.",
		visibility: "Public",
		language: "English",
		age: "18+",
		refundPolicy: "Refunds up to 48 hours before",
		tags: ["film", "indie", "arts", "cinema"],
		ticketTypes: [
			{ name: "Standard Admission", price: 15, sold: 89, capacity: 120 },
		],
	},
	{
		id: "digital-art-workshop",
		title: "Digital Art Workshop",
		category: "Arts & Culture",
		format: "In-Person",
		date: "2025-09-05",
		time: "13:00 – 17:00",
		venue: "MoMA Education Center",
		address: "11 W 53rd St, New York, NY 10019",
		cover: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
		status: "rejected",
		registrations: 0,
		capacity: 30,
		revenue: 0,
		checkedIn: null,
		checkedInCapacity: null,
		description: "Learn digital illustration and design fundamentals with professional artists. Beginners and intermediate artists welcome.",
		visibility: "Public",
		language: "English",
		age: "16+",
		refundPolicy: "Refunds up to 7 days before",
		tags: ["art", "digital", "workshop", "design"],
		rejectionReason: "The event capacity exceeds the venue's maximum occupancy. Please reduce capacity to 20 participants or provide a larger venue.",
		ticketTypes: [
			{ name: "Workshop Seat", price: 75, sold: 0, capacity: 30 },
		],
	},
	{
		id: "marathon-training-bootcamp",
		title: "Marathon Training Bootcamp",
		category: "Sports & Fitness",
		format: "In-Person",
		date: "2025-10-01",
		time: "07:00 – 12:00",
		venue: "Griffith Park",
		address: "4730 Crystal Springs Dr, Los Angeles, CA 90027",
		cover: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80",
		status: "published",
		registrations: 234,
		capacity: 500,
		revenue: 11700,
		checkedIn: null,
		checkedInCapacity: null,
		description: "Intensive training camp for aspiring marathon runners. Expert coaches, personalized plans, nutrition guidance, and group runs.",
		visibility: "Public",
		language: "English",
		age: "18+",
		refundPolicy: "Refunds up to 7 days before",
		tags: ["running", "marathon", "fitness", "training"],
		ticketTypes: [
			{ name: "Training Pass", price: 50, sold: 234, capacity: 500 },
		],
	},
]
